version: '3'
services:
  foundryvtt:
    image: elsuwe/foundryvtt-docker:node-20
    container_name: fvtt
    ports: 
      - "30000:30000"
    volumes:
      - ./data:/data/foundryvtt
      - ./foundry:/opt/foundryvtt
    restart: unless-stopped
